"""initial schema with images and insights tables

Revision ID: 2779222aa63b
Revises: 
Create Date: 2025-11-10 20:46:27.132147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2779222aa63b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    op.create_index(op.f('ix_images_filename'), 'images', ['filename'], unique=False)
    op.create_index(op.f('ix_images_processed'), 'images', ['processed'], unique=False)
    op.create_index(op.f('ix_images_uploaded_at'), 'images', ['uploaded_at'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('dominant_colors', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('brightness', sa.Integer(), nullable=True),
    sa.Column('faces_detected', sa.Integer(), nullable=True),
    sa.Column('face_locations', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('text_found', sa.Boolean(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('sharpness_score', sa.Float(), nullable=True),
    sa.Column('blur_level', sa.String(length=50), nullable=True),
    sa.Column('contrast_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('scene_type', sa.String(length=50), nullable=True),
    sa.Column('scene_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_image_id'), 'insights', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insights_image_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_images_uploaded_at'), table_name='images')
    op.drop_index(op.f('ix_images_processed'), table_name='images')
    op.drop_index(op.f('ix_images_filename'), table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###
